name: Deploy Django App to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Show file tree for debugging
      run: |
        pwd
        ls -lah
        find . -name "requirements.txt"

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r oec-intranet/requirements.txt
      working-directory: ./

    - name: Apply migrations
      run: |
        python oec-intranet/manage.py migrate --noinput
      working-directory: ./

    - name: Collect static files
      run: |
        python oec-intranet/manage.py collectstatic --noinput
      working-directory: ./
    
    - name: Log into Azure using publish profile
      uses: azure/login@v1.6.1
      with:
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: oec-intranet
        slot-name: Production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
        package: .
